name: etexVillagers
version: '${project.version}'
main: me.uranusdestroyer.etexvillagers.etexVillagers
api-version: '1.20'
depend: [etexCore]
authors: [UranusDestroyer]
description: An  etex plugin that revamps the vanilla villager system
